application: shreeautomobiles-1285

version: 1-0

runtime: go

api_version: go1

handlers:
- url: /
  static_files: static/shreelayout.html
  upload: static/shreelayout.html

- url: /shreelayout.html
  static_files: static/shreelayout.html
  upload: static/shreelayout.html

- url: /.*
  script: _go_app
